[tool.poetry]
name = "cbl2py"
version = "0.1.0"
description = "Cobol to Python Translator"
authors = ["Fausto Zanasi"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
